import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/index.css';
import Providers from './Providers';
import getLanguageFromHeaders from '@/i18n/getLanguageFromHeaders';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = getLanguageFromHeaders();

  return (
    <html lang={lang}>
      <body className={inter.className}>
        <Providers lang={lang}>{children}</Providers>
      </body>
    </html>
  );
}
