name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**"

defaults:
  run:
    working-directory: ./react-router-v7-ssr

jobs:
  linting:
    runs-on: ubuntu-latest
    name: Linting - React Router V7 SSR
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Set env to dev
        run: |
          touch .env
          echo "VITE_APP_ENVIRONMENT=dev" >> .env
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
  playwright-integration-tests:
    runs-on: ubuntu-latest
    name: Playwright Integration Tests - React Router V7 SSR
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Set env to dev
        run: |
          touch .env
          echo "VITE_APP_ENVIRONMENT=dev" >> .env
          echo "VITE_APP_MSW_ENABLED=true" >> .env
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm playwright:run-integration
  playwright-e2e-tests:
    runs-on: ubuntu-latest
    name: Playwright E2E Tests - React Router V7 SSR
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Set env to dev
        run: |
          touch .env
          echo "VITE_APP_ENVIRONMENT=dev" >> .env
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm playwright:run-e2e
  unit-tests-coverage:
    runs-on: ubuntu-latest
    name: Unit Tests - React Router V7 SSR
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Unit Tests
        run: pnpm test:coverage
  bundle-size:
    runs-on: ubuntu-latest
    name: Bundle Size - React Router V7 SSR
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build the app
        run: pnpm build
      - name: Bundlesize Check
        run: pnpm bundlesize
